import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:flutter_base/generated/assets.dart';
import 'package:flutter_base/src/config/language/locale_keys.g.dart';
import 'package:flutter_base/src/config/res/color_manager.dart';
import 'package:flutter_base/src/config/res/constants_manager.dart';
import 'package:flutter_base/src/core/extensions/padding_extension.dart';
import 'package:flutter_base/src/core/helpers/helpers.dart';
import 'package:flutter_base/src/core/navigation/navigator.dart';
import 'package:flutter_base/src/core/shared/cubits/user_cubit/user_cubit.dart';
import 'package:flutter_base/src/core/widgets/app_bar.dart';
import 'package:flutter_base/src/core/widgets/app_text.dart';
import 'package:flutter_base/src/core/widgets/buttons/loading_button.dart';
import 'package:flutter_base/src/features/auth/complete_profile/presentation/imports/imports.dart';
import 'package:flutter_base/src/features/auth/send_otp/data/imports/data_imports.dart';
import 'package:flutter_base/src/features/bottom_bar/presentation/imports/imports.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'dart:developer';
import 'package:easy_localization/easy_localization.dart' as localization;
import 'package:flutter_base/src/core/extensions/context_extension.dart';
import 'package:pinput/pinput.dart';
import 'package:smart_auth/smart_auth.dart';
import 'dart:async';

import '../../../../../core/shared/base_state.dart';
import '../../../../../core/shared/models/user_data.dart';
import '../../../../profile/presentation/widgets/timer.dart';
import '../../data/models/send_otp_body.dart';
import '../../data/models/send_otp_response.dart';

part '../screens/send_otp.dart';
part '../widgets/otp_fields.dart';
part '../cubit/otp_cubit.dart';
part '../cubit/otp_state.dart';